services:

  redis:
    image: redislabs/redismod
    container_name: db
    expose:
      - 6379
  todoapp:
    image: node:16
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3333:3333
    environment:
      - REDIS_URL=redis://db
      - NODE_ENV=development
      - PORT=3333
    command:
      sh -c 'yarn install && yarn start'
