services:
  redis:
    image: redislabs/redismod
    container_name: db
    ports:
      - 6379
  todoapp:
    build: .
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://db
      - NODE_ENV=development
      - PORT=3000
    command:
      sh -c 'yarn install && nodemon .'

